services:
  web:
    image: image-web
    container_name: container-web
    hostname: web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html
      - ../certificate:/etc/letsencrypt/archive/www.l2-6.ephec-ti.be/
    networks:
      - api

  php:
    image: image-php
    container_name: container-php
    hostname: php
    environment:
        PHP_USER: ${PHP_USER}
        PHP_PASSWORD: ${PHP_PASSWORD}
        PHP_HOST: ${MARIADB_HOST}
        PHP_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./html:/var/www/html
    networks:
      - api

  mariadb:
    image: mariadb
    container_name: container-mariadb
    hostname: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD} 
        MYSQL_USER: ${MARIADB_USER}
        MYSQL_PASSWORD: ${MARIADB_USER_PASSWORD}
        MYSQL_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/cnf/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - api

networks:
  api: 
